project:
  type: website

website:
  title: "Good enough practices to manage your project data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plan.qmd
        text: Planning
      - href: manage.qmd
        text: Managing
      - href: preserve.qmd
        text: Preserving
      - href: about.qmd
        text: "About RDS"
    tools:
      - icon: github
        menu:
          - text: Website Code
            url:  https://github.com/UCSB-Library-Research-Data-Services/project-data-management
          - text: Report an issue
            url:  https://github.com/UCSB-Library-Research-Data-Services/project-data-management/issues
    
format:
  html:
    theme: 
      - spacelab
      - rdsstyles.scss
    css: styles.css
    toc: true

editor: visual

