---
title: "Data Management Plan"
---

In a nutshell, **your goal as a Data Manager is to organize your team in a way that will let you document and preserve your work** - including raw and derived data when possible. When delivering a project to a client, it is important to make sure the client can both understand and reuse the products (code, data, apps) you have developed. For those reasons more and more funders are requiring a data management plan as part of their proposal submission process and therefore it is a great skill to develop.


Having a plan to manage your data will save you from some potential painful hiccups and therefore save you time s your progress through your project data life cycle. In other words, it is time well spent to develop your data management plan. Note that the team discussion necessary to develop your plan is as important as the plan itself as the questions you will have to answer will help you to think more about your data (what type, how much of it, how are you going to process it,...) and also define who is going to do what on your team.


In the end, the goal is to archive your data in a data repository such as [Dryad](https://datadryad.org/stash). Here is an example of a previous group archive: <https://doi.org/10.25349/D97G9Z> -- especially look at the `README.md` describing the content.


## Developing your Data Management Plan (DMP)

Here are a set of general questions that will help your team to think about the data and resources your will need along the data lifecycle of your project.

1. **Describing the research data**: Provide a description of the data the group will collect or re-use, including the file types, data set size, the number of expected files or sets, content, and source of the data (creator and method of collection).
    i) What data are needed?
    i) Are such data available? 
    i) When and how will the data be acquired? 
    
2. **Data standards**:
    i) Are there any standard formats in the specific research field for managing or disseminating the data sets that have been identified (e.g., XML, ASCII, CSV, .shp, .gdb, GeoTIFF)? 
    i) Who from the group will have responsibility for ensuring that data standards are properly applied and data are properly formatted?
    
3. **Metadata**: Metadata is documentation that helps make data sets reusable. Think about what details (metadata) someone would need in order to be able to understand and use these files. For example, perhaps a `readme.txt` file is necessary to explain variables, the structure of the files, etc. In addition, metadata should follow disciplinary standards, including ontologies and vocabularies. If applicable, describe how the group's models, scripts, and/or workflows will be documented. 

4. **Data sharing and access** The data may have significant value for other researchers beyond this project, and sharing this data is part of the group's responsibility as members of the scientific community. Specify the extent to which data can be reused, including any access limitations. List any proprietary software that might be needed to read the files. If some data is not appropriate for sharing due to confidentiality, NDA, or disclosure risk, then describe that here. 

5. **Intellectual property and re-use**:  If data were collected from the client organization, does the group have the right to redistribute it? If so, are there any restrictions on redistribution? If the group created its data files, will it assign a Creative Commons license to its data? 

6. **Data archiving and preservation**: Throughout the project, the group may produce a large number of files. At the end of the project, groups must submit data used in the project (except data protected by non-disclosure agreements) and associated metadata. Not all data needs to be saved. If another researcher wanted to replicate the group's work or re-use the group's data, what data and documentation would be required for them to do so? Where will the data and metadata be stored after the project is completed? Is there a subject-specific and/or open-access repository that is appropriate for the data?


## Data Management Plan Tool

There is a tool that you can use to guide your process: **the DMP Tool**. It is a little bit like an online form on steroids. Note that you do not have to use this tool for your project, but from our experience, it provides good guidance for this process.

-   (Almost) everything in one page: <https://www.library.ucsb.edu/sites/default/files/dls-n05-2022-dmptool-navy_0.pdf>

<iframe width="100%" height="1000" src="https://www.library.ucsb.edu/sites/default/files/dls-n05-2022-dmptool-navy_0.pdf">

</iframe>

-   Guidelines on how to use the Data Management Tool to develop your plan: <https://doi.org/10.5281/zenodo.7566971>

-   Get started with the tool: <http://dmptool.org/>\
    *Make sure to create an account using your UCSB email!*
    

## Using your Data Management Plan

Ok, you have a plan, and now what!?  **A data management plan should be seen as a living document** that you update as your project develops and data needs evolve. We thus recommend sharing this plan with all your team members and external partners when relevant. The DMP Tool has the capacity to share plans directly from the tool. If you do not choose to use it, we recommend choosing a file format that can be collectively edited and provide some versioning / track changes, such as Google Docs or other cloud-based storage and documents.




