---
title: "Archiving and preserving your data"
---


As you are finalizing your project, an important task is to archive your data in a publicly available repository (pending sensitivity and by non-disclosure agreement exceptions). There are a few important steps to take to make sure that your data can be reused by others and make your work more reproducible.


## What scientific products to preserve?

It is often the first question that comes to mind: What should I include in my data archive. Generally speaking you want to preserve your work, so any data and analayses you conducted to come to the conclusions discussed in your report and other publications 

### Raw data

- often not re-obtainable
- supports inspection, backtracing
- contains information lost in aggregation process

### Intermediate data

- if has reusable value
- especially cleaned-up versions of raw data!

### Final products

- including raw data behind graphs, maps, visualizations




## Documenting your work

To make your archiving process the most efficient, it is key to document your work as you progress throughout your project. If you do so, archiving your data will mostly be collecting existing information about the various parts of your project.

### Metadata

Are the raw data you used already publicly available? If so simply cite them, otherwise seek the necessary information to know if you could archive those data as well.


Associated metadata and other documentation need to be developed and uploaded with the data.


### README


## Using open file formats



## Choosing a data repository

UCSB's institutional data repository [DRYAD](https://datadryad.org/stash) will be your default data repository. However, we encourage you to discuss with your Faculty Advisor to determine if other data repository options specific to your project topic could be more targeted to your project audience. 



## Choosing a license

DRAYD is CC0



